version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    mapping local files to Docker files (automatically)
    volumes:
      - .:/code
    ports:
      - "8000:8000"